name: 测试构建

on: workflow_dispatch
#   [push]


jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
       include:
#          - platform: bromolow
#            version: 6.2.4-25556
#          - platform: bromolow
#            version: 7.0-41222
#          - platform: bromolow
#            version: 7.0.1-42218
#          - platform: apollolake
#            version: 6.2.4-25556
#          - platform: apollolake
#            version: 7.0-41890
         - platform: apollolake
           version: 7.0.1-42218
    steps:
      - name: 准备结束
        uses: actions/checkout@v2

      - name: 缓存加速
        uses: actions/cache@v2
        with:
          path: |
            cache/*.pat
            docker/downloads/*.txz
          key: ${{matrix.platform}}-${{matrix.version}}-${{ hashFiles('global_config.json') }}

      - name: 准备构建环境
        run: |
          ./redpill_tool_chain.sh build ${{matrix.platform}}-${{matrix.version}}

      - name: 配置引导镜像
        run: |
          cp sample_user_config.json ${{matrix.platform}}_user_config.json
          cat ${{matrix.platform}}_user_config.json
          ./redpill_tool_chain.sh add https://github.com/jumkey/redpill-load/raw/develop/redpill-virtio/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/jumkey/redpill-load/develop/redpill-acpid/rpext-index.json
          ./redpill_tool_chain.sh add https://github.com/jumkey/redpill-load/raw/develop/redpill-boot-wait/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/e1000/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/igb/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/r8101/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/r8125/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/r8152/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/r8168/rpext-index.json


      - name: 编译引导镜像
        run: ./redpill_tool_chain.sh auto ${{matrix.platform}}-${{matrix.version}}


      - name: 上传引导镜像到 github actions
        uses: actions/upload-artifact@v2
        with:
          name: dsm-${{matrix.platform}}-${{matrix.version}}
          path: images/redpill-DS[39]*.img
          if-no-files-found: error


